### ISSUE TITLE
部署web host的几种方法(Apache,nginx,node.js)

### ISSUE THREAD

**Issue by BarryLe** [cccc-engineer/Praying#1]
每个人尝试添加探索一个感兴趣的github网页项目并做简短的介绍
黄大哥：部署web host的几种方法(Apache,nginx,node.js)

**Comment by littleflute** [comment]
78b2a69cddba28b95e387e7bf1ab318e749984d3b1ea7852b14b7fdd0dc1edb0
https://dashboard.daily.co/onboarding

**Comment by littleflute** [comment]
https://docs.daily.co/docs
