### ISSUE TITLE
create swagger API file

### ISSUE THREAD

**Issue by BarryLe** [cccc-engineer/Praying#12]
post login
get {user}
post logout

etc
http://livingpraying.org/
http://livingpraying.org:3000/

**Comment by littleflute** [comment]
http://localhost:3000/api-doc/#/

**Comment by littleflute** [comment]
http://localhost:3000/openapi

**Comment by littleflute** [comment]
http://localhost:3000/

**Comment by littleflute** [comment]
https://068276223463.signin.aws.amazon.com/console
https://lihaoz8.wixsite.com/main/post/how-to-login-our-aws-server
(yonglin xd1****0)

**Comment by littleflute** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html#putty-scp

**Comment by littleflute** [comment]
https://reactjs.org/tutorial/tutorial.html

**Comment by littleflute** [comment]
https://getbootstrap.com/

**Comment by BarryLe** [comment]
Run backend node server on our "livingpraying" ec2 instance.

1. download private key: https://drive.google.com/file/d/1feNozJrd6iGVGMnxudq7kBRTGODVTdBp/view?usp=sharing

2. follow the official AWS putty setup tutorial: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html#putty-scp

3. transfer the swagger backend folder in /home/ubuntu/

4. running the app.js by run: "pm2 start app.js" in the new folder

5. test the swagger output by running: curl localhost:3000
If you are able to see the HTML codes, it means we have got this server running properly.

EXTRA:
1. Explore AWS API Gateway concepts to see if it's helpful for our project. https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html
Feel free to summarize any new AWS gateway knowledge by posting an article on our blog: https://lihaoz8.wixsite.com/main/blog

2.If you have dummy database data behind APIs, you can try to query them in the front end codes.
Modify: /home/ubuntu/run/app.js 

After making changes in front end app.js, run "pm2 reload 0" to reload the front end app.js.

**Comment by littleflute** [comment]
https://aws.amazon.com/cn/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/

**Comment by littleflute** [comment]
https://github.com/aws-samples/simple-websockets-chat-app
