### ISSUE TITLE
Implement login apis base on new yaml file

### ISSUE THREAD

**Issue by BarryLe** [cccc-engineer/Praying#18]
yl1 branch is ready to be merged. Feel free to create the pull request.

Start to implement login APIs includes: 

- [x] post/signup  

- [x] post/login  

There three basic API should allow creating a new account and login with the correct password.

**Comment by littleflute** [comment]
https://greensock.com/position-parameter/

**Comment by littleflute** [comment]
http://livingpraying.org:8080/

**Comment by littleflute** [comment]
[node]
npm test
node index.js

**Comment by littleflute** [comment]
加入 Zoom 会议
https://oregonstate.zoom.us/j/8758410962?pwd=Rit0R09leENROVJ6U0EzUitwdlN0UT09
https://github.com/littleflute/BeautifulLover/issues/356

**Comment by littleflute** [comment]
https://medium.com/@jackrobertscott/how-to-use-google-auth-api-with-node-js-888304f7e3a0
